### PR TITLE
switch/match default case + type propagation for interop method calls

### PR DESCRIPTION
**Pull request by echeran**
WIP a.t.m.

### CODE REVIEW

**Comment by timothypratley** [comment]
the good old `resolve-t` should have been `resolve-tag` trick. `resolve-t` operates on imetas, where `resolve-tag` operates on the tag directly o_O 😕 Well, it's working now, that's good! :)

**Review by timothypratley — APPROVED** [review]
🚀 great 👍

**Comment by echeran** [comment]
Nice catch! I think that corresponds with what we were hoping - after the AST pass, we should be looking at `:t`, not `:tag`.

I added some docstrings and similar comments for some of the helper fns and macros as a way to ensure & reinforce my understanding of what's going on.

Can you verify that the new comments make sense? I'll merge once they look accurate.

I also added a new test that's similar but left it commented out because it requires some work. I think it requires us to create a reusable mechanism of translating interop types to target language types. It may not be hard, like it could be as simple as just a map in `k.p.types`.

**Comment by timothypratley** [comment]
Sweet, nice improvements.

> Can you verify that the new comments make sense? I'll merge once they look accurate.

done, look perfect! 👍 

:shipit:

**Pull request merged**
