### PR TITLE
[WIP] Host Interop

### PR DESCRIPTION
**Pull request by mvid**
Created a basic test, with the intention of getting a failure on not having a case in curlybrace.clj:937 for :host-interop. However, instead I am getting no error, and just no result for the `System/getenv` call. 

Any ideas on where I should be looking?

### CODE REVIEW

**Comment by echeran** [comment]
I had a difficult time finding a testing strategy that worked for me.  I wanted to use expectations, but the features I like most about it were difficult to make compatible with the clojure.test style that CIDER, Cursive, etc. support.  The `expectations.clojure.test` version of expectations is okay, but still doesn't match the experience I had.  Anyways, what it forced me to do for running tests was to run them at the command line.  According to the [Readme](https://github.com/clojure-expectations/clojure-test), you can format the output using the [Humane Output library](https://github.com/pjstadig/humane-test-output).

When running `lein test` at the command line, I get:

```
lein test :only kalai.demo.demo03-host-interop-test/demo03

FAIL in (demo03) (demo03_host_interop_test.clj:19)
java

expected: (=? ["" "public class HostInterop\n{\n  public String printEnvVariables()\n  {\n    String envEditor = System.getenv(\"EDITOR\");\n    return envEditor;\n  }\n}\n"] java-strs)
  actual: (not (=? ["" "public class HostInterop\n{\n  public String printEnvVariables()\n  {\n    String envEditor = System.getenv(\"EDITOR\");\n    return envEditor;\n  }\n}\n"] ("" "public class HostInterop\n{\n  public String printEnvVariables()\n  {\n    {\n      String envEditor = \"EDITOR\";\n      return envEditor;\n    }\n  }\n}")))
```

Symptomatic of the split mind that occurs when `expectations` is used in places where the usual `clojure.test` tooling is present, you can get both test frameworks test output reporting:

```
Ran 176 tests containing 386 assertions.
1 failures, 0 errors.

Ran 0 tests containing 0 assertions in 0 msecs
0 failures, 0 errors.
```

Part of the motivation for desiring a better testing library is to catch the minor discrepancies in tests.  For example, in your test expected output, you have an extra newline at the end.

One thing that we discussed in the ongoing PR was the importance of testing that hits the small set of functionality from `expectations` that we want (esp the intelligent string comparison, and have it work for multi-line strings).  We arrived at the test helper [`placation.clj`](https://github.com/echeran/kalai/blob/tim/propose-normalization/test/kalai/placation.clj), and you apparently only need to require it in your tests namespace ([example](https://github.com/echeran/kalai/blob/tim/propose-normalization/test/kalai/pass/test_helpers.clj#L7) of it being commented out), and if your tests are written using `clojure.test`, you'll get our error reporting functions instead of the default kind.

**Comment by mvid** [comment]
@echeran I don't so much mind the string comparison issues, it was more that I was expecting to get a failure matching the case from the output AST, since `:host-interop` is something that isn't defined in `iface/emit` for curlybrace or java implementations. Also, instead of anything breaking, it seems to just omit the expected 
`String envEditor = System.getenv(\"EDITOR\");\n`
and output 
`String envEditor = \"EDITOR\";\n`

That skipped action seems bad, no?

**Comment by mvid** [comment]
For instance, I added another line to the test that tries to call an instance method on the first bound string. It fails with a stacktrace, because `:instance-call` has not been implemented. But the static method call fails silently.

**Review by timothypratley — APPROVED** [review]
I think this will be a useful demo;
We have reached a good place on the term re-writting branch "nanopass" and will revisit this example after that gets merged.
In the meantime let's add this example here.

**Pull request merged**
